version: '3'

services:
  db:
    image: postgres:12.0-alpine
    env_file:
      - microblog_backend/.env
    volumes:
      - ./microblog_backend/postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
  web:
    build: 
      context: microblog_backend
      dockerfile: Dockerfile
    volumes:
      - ./microblog_backend/:/app
    ports:
      - 8000:8000
    env_file:
      - microblog_backend/.env
    depends_on:
      - db
  celery:
    build: microblog_backend
    command: bash -c "pip install redis && celery worker -A microblog_backend -l INFO -B"
    volumes:
      - ./microblog_backend/:/app
    env_file:
      - microblog_backend/.env
    depends_on:
      - web
      - redis
  redis:
    image: redis:6.2.1-alpine
  front:
      build: ./microblog_frontend
      volumes:
        - ./microblog_frontend:/front
        - /front/node_modules
      ports:
        - "3000:3000"
      env_file:
        - microblog_backend/.env
      depends_on:
        - db
      command: npm start
      stdin_open: true
