# Generated by Django 3.2.2 on 2021-05-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210517_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='users',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
