# Generated by Django 3.2.2 on 2021-05-16 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20210517_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
        migrations.AddField(
            model_name='vote',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='option_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='vote_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
