# Generated by Django 3.2.2 on 2021-05-16 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210517_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vote',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.vote'),
        ),
    ]
